export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_NEW_USER = 'SET_NEW_USER'
export const SHOW_PROJECTS = "SHOW_PROJECTS"
export const FIND_PROJECT = 'FIND_PROJECT'
export const SET_NEW_PROJECT = 'SET_NEW_PROJECT'
export const ADD_PROJECT_TO_PROJECTS = 'ADD_PROJECT_TO_PROJECTS'
export const FIND_USER_PROJECTS = 'FIND_USER_PROJECTS'
